name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies, Copy ENV, Generate Key, Migrate and Test
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
        php -r "file_exists('.env') || copy('.env.testing', '.env');" && php artisan key:generate && php artisan migrate --seed && vendor/bin/phpunit
